version: '3'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_MODE=debug
      - SERVER_ALLOWED_HOSTS=*
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MTN_BASE_URL=${MTN_BASE_URL}
      - MTN_API_KEY=${MTN_API_KEY}
      - MTN_API_SECRET=${MTN_API_SECRET}
      - MTN_MOCK_API=${MTN_MOCK_API}
      - SMS_DEFAULT_GATEWAY=${SMS_DEFAULT_GATEWAY}
      - SMS_MOCK_SMS=${SMS_MOCK_SMS}
      - SMS_MTN_BASE_URL=${SMS_MTN_BASE_URL}
      - SMS_MTN_API_KEY=${SMS_MTN_API_KEY}
      - SMS_MTN_API_SECRET=${SMS_MTN_API_SECRET}
      - SMS_KODOBE_BASE_URL=${SMS_KODOBE_BASE_URL}
      - SMS_KODOBE_API_KEY=${SMS_KODOBE_API_KEY}
    restart: always
