version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: bridgetunes-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bridgetunes-network
    restart: unless-stopped

  # Backend API service
  backend:
    build:
      context: ./bridgetunes-mtn-backend
      dockerfile: Dockerfile
    container_name: bridgetunes-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=bridgetunes
    networks:
      - bridgetunes-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./bridgetunes-fixed-imports
      dockerfile: Dockerfile
    container_name: bridgetunes-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    networks:
      - bridgetunes-network
    restart: unless-stopped

networks:
  bridgetunes-network:
    driver: bridge

volumes:
  mongodb_data:
