version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: bridgetunes-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bridgetunes-network
    restart: unless-stopped

  # Backend API service
  backend:
    build:
      context: ./bridgetunes-mtn-backend # Assumes docker-compose.yml is one level up
      dockerfile: Dockerfile
    container_name: bridgetunes-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      # Use MONGODB_URI to match the code
      - MONGODB_URI=mongodb://mongodb:27017 # This value is for connecting to the Compose MongoDB service
      # Use MONGO_DB_NAME to match the code
      - MONGO_DB_NAME=bridgetunes
      # Add PORT variable as the code now reads it
      - PORT=8080
    networks:
      - bridgetunes-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./bridgetunes-fixed-imports # Assumes frontend code is in this directory relative to docker-compose.yml
      dockerfile: Dockerfile
    container_name: bridgetunes-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # Consider using http://backend:8080/api/v1 if frontend needs to access backend via Docker network
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    networks:
      - bridgetunes-network
    restart: unless-stopped

networks:
  bridgetunes-network:
    driver: bridge

volumes:
  mongodb_data:
