name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL_ID }}/providers/${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set Google Cloud project
        uses: google-github-actions/setup-cloud-sdk@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Tag and Push Docker image
        run: docker tag bridgetunes-mtn-backend gcr.io/${{ secrets.GCP_PROJECT_ID }}/bridgetunes-mtn-backend && docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bridgetunes-mtn-backend

      - name: Deploy to Cloud Run
        run: gcloud run deploy bridgetunes-mtn-backend --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bridgetunes-mtn-backend --set-env-vars JWT_SECRET=